import { useState } from 'react'
import { FileText, Download, Copy, Printer, Loader2, AlertTriangle, Sparkles } from 'lucide-react'
import { toast } from 'sonner'
import { fetchCases, fetchCase, fetchReport, ApiError } from '@/lib/api'
import type { CaseRow, CaseDetail } from '@/lib/backend'
import { useApiData } from '@/lib/useApi'
import { normSeverity, sevHex, flattenIocs } from '@/lib/format'
import IncidentReport, { type ReportSnapshot } from '@/components/IncidentReport'

// Assemble a full structured incident report in Markdown — mirrors the on-screen
// sections so the downloaded/copied artifact is the same professional document.
function buildReportMarkdown(detail: CaseDetail, narrative: string, generatedAt: string): string {
  const snap = (detail.snapshot as ReportSnapshot | undefined) || {}
  const a = snap.analysis
  const sev = normSeverity(a?.severity || detail.severity).toUpperCase()
  const iocs = flattenIocs(snap.iocs)
  const techniques = snap.mitre?.techniques ?? []
  const events = snap.timeline?.events ?? []
  const recs = a?.recommendations ?? []
  const threats = a?.threats ?? []
  const notes = (detail.audit ?? []).filter((n) => n.entry_type === 'note' && n.content)

  const L: string[] = []
  L.push(`# SecureRAG — Incident Report`)
  L.push('')
  L.push(`**${sev} severity incident — ${detail.title}**`)
  L.push('')
  L.push('## Incident Metadata')
  L.push('')
  L.push(`| Field | Value |`)
  L.push(`|---|---|`)
  L.push(`| Case ID | \`${detail.case_id}\` |`)
  L.push(`| Status | ${String(detail.status || '').replace('_', ' ')} |`)
  L.push(`| Severity | ${sev} |`)
  L.push(`| Owner | ${detail.assigned_to || detail.created_by || '—'} |`)
  L.push(`| Opened | ${detail.created_at} |`)
  L.push(`| Last updated | ${detail.updated_at || detail.created_at} |`)
  L.push(`| Report generated | ${generatedAt} |`)
  if (detail.query) {
    L.push('')
    L.push(`> **Originating query:** ${detail.query}`)
  }
  L.push('')
  L.push('## Executive Summary')
  L.push('')
  if (a?.summary) L.push(`_${a.summary}_`, '')
  L.push(a?.answer?.trim() || narrative.trim() || 'No analysis narrative is available for this case.')

  if (threats.length) {
    L.push('', '## Key Threats', '')
    threats.forEach((t) => L.push(`- ${t}`))
  }

  L.push('', `## Indicators of Compromise (${iocs.length})`, '')
  if (iocs.length === 0) {
    L.push('No indicators of compromise were extracted for this investigation.')
  } else {
    const byType = iocs.reduce<Record<string, string[]>>((m, io) => {
      (m[io.type] ??= []).push(io.value)
      return m
    }, {})
    Object.entries(byType).forEach(([type, vals]) => L.push(`- **${type.toUpperCase()}:** ${vals.join(', ')}`))
  }

  L.push('', `## MITRE ATT&CK (${techniques.length})`, '')
  if (techniques.length === 0) {
    L.push('No ATT&CK techniques were mapped for this investigation.')
  } else {
    L.push('| Technique | Name | Tactic | Confidence |', '|---|---|---|---|')
    techniques.forEach((t) => L.push(`| ${t.technique} | ${t.name} | ${t.tactic} | ${t.confidence} |`))
  }

  L.push('', `## Attack Timeline (${events.length})`, '')
  if (events.length === 0) {
    L.push(snap.timeline?.summary || 'No timeline events were reconstructed.')
  } else {
    events.forEach((ev) =>
      L.push(`- \`${ev.timestamp}\` **${ev.event_type}**${ev.mitre_technique ? ` (${ev.mitre_technique})` : ''} — ${ev.description}`),
    )
  }

  L.push('', `## Recommendations`, '')
  if (recs.length === 0) {
    L.push('No remediation recommendations were generated.')
  } else {
    recs.forEach((r, i) => L.push(`${i + 1}. ${r}`))
  }

  if (notes.length) {
    L.push('', '## Analyst Notes', '')
    notes.forEach((n) => L.push(`- ${n.content}  \n  _— ${n.author}, ${n.created_at}_`))
  }

  L.push('', '---', `_Generated by SecureRAG · ${generatedAt} · Case ${detail.case_id.slice(0, 8)} · Confidential._`)
  return L.join('\n')
}

export default function Reports() {
  const { status, data, error, reload } = useApiData<CaseRow[]>(() => fetchCases())
  const cases = data ?? []

  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [genStatus, setGenStatus] = useState<'idle' | 'loading' | 'ready' | 'error'>('idle')
  const [detail, setDetail] = useState<CaseDetail | null>(null)
  const [narrative, setNarrative] = useState('')
  const [generatedAt, setGeneratedAt] = useState('')
  const [genError, setGenError] = useState('')

  const generate = async (c: CaseRow) => {
    setSelectedId(c.case_id)
    setGenStatus('loading')
    setGenError('')
    setDetail(null)
    try {
      // Full case context (fields + audit/notes + snapshot with iocs/mitre/timeline).
      const d = await fetchCase(c.case_id)
      const snapshot = d.snapshot as { analysis?: unknown } | undefined
      const analysis = snapshot?.analysis
      // The narrative is the backend's generated report text; it needs an analysis
      // object. Without one we still render the structured report from the snapshot.
      let text = ''
      if (analysis) {
        try { text = await fetchReport(analysis) } catch { /* narrative falls back to analysis.answer */ }
      }
      setDetail(d)
      setNarrative(text)
      setGeneratedAt(new Date().toLocaleString())
      setGenStatus('ready')
    } catch (e) {
      setGenStatus('error')
      setGenError(e instanceof ApiError ? e.message : 'Report generation failed.')
    }
  }

  const download = () => {
    if (!detail) return
    const md = buildReportMarkdown(detail, narrative, generatedAt)
    const blob = new Blob([md], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `incident-report-${detail.case_id.slice(0, 8)}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  const copy = () => {
    if (!detail) return
    navigator.clipboard.writeText(buildReportMarkdown(detail, narrative, generatedAt))
      .then(() => toast.success('Report copied (Markdown)'))
  }

  return (
    <div className="mx-auto max-w-[1300px] p-8">
      <div className="mb-6 no-print">
        <div className="flex items-center gap-2">
          <FileText size={18} className="text-sr-accent" />
          <h2 className="font-display text-xl font-bold text-sr-text">Reports</h2>
        </div>
        <p className="mt-1 text-sm text-sr-text-secondary">Generate a professional incident report from a saved investigation.</p>
      </div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-[340px_1fr]">
        {/* Case list */}
        <div className="rounded-lg border border-sr-border bg-sr-surface card-shadow no-print">
          <div className="border-b border-sr-border px-4 py-3 text-[11px] font-medium uppercase tracking-wider text-sr-text-secondary">
            Saved cases ({cases.length})
          </div>
          <div className="max-h-[560px] divide-y divide-sr-border overflow-y-auto">
            {status === 'loading' && (
              <div className="flex items-center gap-2 px-4 py-5 text-sm text-sr-text-secondary">
                <Loader2 size={15} className="animate-spin" /> Loading…
              </div>
            )}
            {status === 'error' && (
              <div className="px-4 py-5 text-sm text-sr-red">
                <AlertTriangle size={14} className="mr-1 inline" /> {error}
                <button onClick={reload} className="ml-2 text-xs underline">Retry</button>
              </div>
            )}
            {status === 'ready' && cases.length === 0 && (
              <p className="px-4 py-6 text-center text-xs text-sr-text-tertiary">
                No cases yet. Save a query as a case to generate reports.
              </p>
            )}
            {cases.map((c) => {
              const sc = sevHex(normSeverity(c.severity))
              return (
                <button
                  key={c.case_id}
                  onClick={() => generate(c)}
                  className={`flex w-full items-start gap-3 px-4 py-3 text-left transition-colors hover:bg-sr-elevated ${selectedId === c.case_id ? 'bg-sr-elevated' : ''}`}
                >
                  <span className="mt-1.5 h-2 w-2 shrink-0 rounded-full" style={{ background: sc }} />
                  <div className="min-w-0">
                    <div className="truncate text-sm font-medium text-sr-text">{c.title}</div>
                    <div className="font-mono text-[10px] text-sr-text-tertiary">{c.case_id.slice(0, 8)} · {(c.created_at || '').slice(0, 10)}</div>
                  </div>
                </button>
              )
            })}
          </div>
        </div>

        {/* Report viewer */}
        <div className="min-h-[400px] rounded-lg border border-sr-border bg-sr-surface card-shadow">
          {genStatus === 'idle' && (
            <div className="flex h-full min-h-[400px] flex-col items-center justify-center gap-2 text-sr-text-tertiary no-print">
              <Sparkles size={24} />
              <p className="text-sm">Select a case to generate its incident report.</p>
            </div>
          )}
          {genStatus === 'loading' && (
            <div className="flex h-full min-h-[400px] items-center justify-center gap-2 text-sr-text-secondary no-print">
              <Loader2 size={18} className="animate-spin" /> Generating report…
            </div>
          )}
          {genStatus === 'error' && (
            <div className="flex h-full min-h-[400px] items-center justify-center px-6 text-center text-sm text-sr-red no-print">
              <span><AlertTriangle size={15} className="mr-1 inline" /> {genError}</span>
            </div>
          )}
          {genStatus === 'ready' && detail && (
            <div className="flex h-full flex-col">
              <div className="flex items-center justify-between border-b border-sr-border px-5 py-3 no-print">
                <span className="text-sm font-semibold text-sr-text">Incident Report</span>
                <div className="flex items-center gap-2">
                  <button onClick={() => window.print()} className="flex items-center gap-1.5 rounded border border-sr-border px-2.5 py-1 text-xs text-sr-text-secondary hover:text-sr-text">
                    <Printer size={12} /> Print / PDF
                  </button>
                  <button onClick={copy} className="flex items-center gap-1.5 rounded border border-sr-border px-2.5 py-1 text-xs text-sr-text-secondary hover:text-sr-text">
                    <Copy size={12} /> Copy
                  </button>
                  <button onClick={download} className="flex items-center gap-1.5 rounded border border-sr-border px-2.5 py-1 text-xs text-sr-text-secondary hover:text-sr-text">
                    <Download size={12} /> Download
                  </button>
                </div>
              </div>
              <div className="flex-1 overflow-auto">
                <IncidentReport detail={detail} narrative={narrative} generatedAt={generatedAt} />
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
